### ISSUE TITLE
flare_flutter-1.5.0 Error

### ISSUE THREAD

**Issue by YourksChan** [2d-inc/Flare-Flutter#86]
Compiler message:                                                       
file:///Users/yourks/.pub-cache/hosted/pub.flutter-io.cn/flare_flutter-1.5.0/lib/flare.dart:1023:18: Error: The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.                               
 - 'Uint16List' is from 'dart:typed_data'.                              
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
        indices: _indices, textureCoordinates: _uvBuffer);              
                 ^                                                      
Compiler terminated unexpectedly.

**Comment by EliasDeuss** [comment]
getting the same error

**Comment by luigi-rosso** [comment]
This is due to breaking changes in the latest flutter master,  these are not present in stable or 1.5.4, so right now we recommend using Flutter version 1.5.4 and soon we'll supply a custom branch that you can use if you are using a more bleeding edge version Flutter.

**Comment by luigi-rosso** [comment]
You can point your pubspec to our latest dev if you are using a non-stable version of flutter, this will work for the issue above:
```
flare_flutter:
  git: 
    url: git://github.com/2d-inc/Flare-Flutter.git
    ref: dev
    path: flare_flutter
```

**Comment by mdanics** [comment]
Running dev still getting this error

**Comment by luigi-rosso** [comment]
That's odd, it's definitely fixed in dev:
https://github.com/2d-inc/Flare-Flutter/blob/c51192dec50dec034d121f6aad7d2e8733c7e279/flare_flutter/lib/flare.dart#L914

Maybe try calling flutter pub get one more time.

**Comment by mdanics** [comment]
Tried flutter clean, deleting pub cache still getting the error :(

**Comment by mdanics** [comment]
fresh install of my repo and it worked, guess there is some caching issue with pub/flutter

**Comment by mdanics** [comment]
Ah apologies, it looks like the error I am getting is slightly different, the types are swapped. See below

`Error: The argument type 'Uint16List' can't be assigned to the parameter type 'Int32List'.`

**Comment by luigi-rosso** [comment]
Can you run ```flutter doctor``` and post the results? This change had been rolled into dev a few days ago, I wonder if they reverted it.

**Comment by mdanics** [comment]
ah, i'm using stable. i'll try with master.

Here's the doctor results

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.3 18D109, locale
    en-CA)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.33.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.
```

**Comment by mdanics** [comment]
Works with master!

**Comment by JAICHANGPARK** [comment]
I had same problems... 
anyone solved this problem? 
```
 flare_flutter:
    git: 
      url: git://github.com/2d-inc/Flare-Flutter.git
      ref: dev
      path: flare_flutter
```

```
Compiler message:
file:///Users/myname/.pub-cache/git/Flare-Flutter-c51192dec50dec034d121f6aad7d2e8733c7e279/flare_flutter/lib/flare.dart:1022:18: Error: The
argument type 'Uint16List' can't be assigned to the parameter type 'Int32List'.
 - 'Uint16List' is from 'dart:typed_data'.
 - 'Int32List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Int32List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^
Compiler failed on /Users/myname/Desktop/temp_flare/Flare-Flutter/example/teddy/lib/main.dart
Error launching application on iPhone XR.
```

**Comment by luigi-rosso** [comment]
@JAICHANGPARK please make sure you on the dev channel of flutter. You can do this on the command line by typing:
```flutter channel dev```

We are closing this issue as the problem has been fixed. If you are still seeing this error, please make sure you are using the correct branch with the matching flutter channel. The details are clearly provided in our [README](https://github.com/2d-inc/Flare-Flutter/blob/3a6d42f772b8db6d58155081e1f35cecd6f829c1/README.md).
